name: mcmodpackmanager_reborn
description: Manage your modpacks with ease!
publish_to: 'none'

version: 7.5.0+0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_platform_widgets: ^3.0.0
  dynamic_color: ^1.6.2
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_localizations:
    sdk: flutter
  intl: any
  ffi: ^2.0.1
  window_manager: ^0.3.1
  package_info_plus: ^3.0.3
  file_picker: ^5.2.5
  http: ^0.13.5
  path_provider: ^2.0.13
  archive: ^3.3.6
  flutter_platform_alert: ^0.3.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  msix: ^3.9.1
  flutter_launcher_icons: ^0.12.0
flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/icons/logohalf.png

flutter_icons:
  windows:
    generate: true
    image_path: assets/icons/logo.ico
    icon_size: 128
  macos:
    generate: true
    image_path: assets/icons/logohalf.png
    icon_size: 256
msix_config:
  display_name: MC Modpack Manager
  publisher_display_name: MrQuantumOFF (Demir Yerli)
  publisher: CN=010914FC-8843-4963-A3FE-E3E06E6D9F53
  identity_name: 58734MrQuantumOFFDemirYer.MinecraftModpackManagerR
  msix_version: 7.5.0.0
  logo_path: .\assets\icons\logo.png
  store: true
  languages: en-us, uk-ua
  capabilities: internetClient, broadFileSystemAccess