name: mcmodpackmanager
base: core22
version: 'v6.4.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Manage your modpacks with ease!
description: |
  Change your modpack by clicking just a few buttons!
  This app lets you install and manage minecraft modpacks using a GUI written in Flutter and Dart.
  NOTE: This app and its developer are not affiliated with Mojang Studios.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64

parts:
  mcmodpackmanager:
    build-snaps:
      - flutter
    build-packages:
      - wget
    plugin: nil
    override-build: |
        wget https://github.com/mrquantumoff/mcmodpackmanager_reborn/releases/download/v6.4.0/GNULinuxBuild.tar.gz
        tar -xpvf GNULinuxBuild.tar.gz
        mkdir -p $SNAPCRAFT_PART_INSTALL/mcmodpackmanager
        cp -r build/linux/x64/release/bundle/* $SNAPCRAFT_PART_INSTALL/mcmodpackmanager
apps:
  mcmodpackmanager:
    command: mcmodpackmanager/mcmodpackmanager_reborn
    common-id: dev.mrquantumoff.mcmodpackmanager
