name: mcmodpackmanager
base: core22
version: 'v6.4.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Manage your modpacks with ease!
description: |
  Change your modpack by clicking just a few buttons!
  This app lets you install and manage minecraft modpacks using a GUI written in Flutter and Dart.
  NOTE: This app and its developer are not affiliated with Mojang Studios.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64

parts:
  mcmodpackmanager:
    build-snaps:
      - flutter
    plugin: flutter
    # stage-packages:
    #  - libepoxy0
    #  - libgtk-3-0
    source: https://github.com/mrquantumoff/mcmodpackmanager_reborn.git
    source-tag: v6.4.0
apps:
  mcmodpackmanager:
    command: mcmodpackmanager_reborn
    common-id: dev.mrquantumoff.mcmodpackmanager
    extensions: [gnome]
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl