name: mcmodpackmanager
base: core22
version: 'v6.5.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Manage your modpacks with ease!
description: |
  Change your modpack by clicking just a few buttons!
  This app lets you install and manage minecraft modpacks using a GUI written in Flutter and Dart.
  NOTE: This app and its developer are not affiliated with Mojang Studios.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64

layout:
  /usr/share/icons/hicolor/256x256/apps/dev.mrquantumoff.mcmodpackmanager.png:
    bind-file: $SNAP/usr/share/icons/hicolor/256x256/apps/dev.mrquantumoff.mcmodpackmanager.png
  /var/minecraft:
    symlink: $SNAP_DATA/minecraft
parts:
  desktop-metadata:
    plugin: nil
    build-packages:
      - wget
    source: 'https://github.com/mrquantumoff/mcmodpackmanager_reborn.git'
    source-tag: v6.5.2
    override-build: |
      mkdir -p usr/share/metainfo
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      mv dev.mrquantumoff.mcmodpackmanager.metainfo.xml /usr/share/metainfo
      mv assets/icons/logohalf.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/dev.mrquantumoff.mcmodpackmanager.png
      mv dev.mrquantumoff.mcmodpackmanager.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/dev.mrquantumoff.mcmodpackmanager.desktop
    parse-info: [usr/share/metainfo/dev.mrquantumoff.mcmodpackmanager.metainfo.xml]
  mcmodpackmanager:
    build-packages:
      - wget
    build-snaps:
      - flutter
    plugin: nil
    override-build: |
        wget https://github.com/mrquantumoff/mcmodpackmanager_reborn/releases/download/v6.5.2/GNULinuxBuild.tar.gz
        tar -xpvf GNULinuxBuild.tar.gz
        mkdir -p $SNAPCRAFT_PART_INSTALL/mcmodpackmanager
        cp -r build/linux/x64/release/bundle/* $SNAPCRAFT_PART_INSTALL/mcmodpackmanager
apps:
  mcmodpackmanager:
    desktop: usr/share/applications/dev.mrquantumoff.mcmodpackmanager.desktop
    command: mcmodpackmanager/mcmodpackmanager_reborn
    common-id: dev.mrquantumoff.mcmodpackmanager
    environment:
     SNAP_RUNTIME: 0
